# Dependencies
markdown:         redcarpet
highlighter:      pygments


# Permalinks
permalink:        pretty
relative_permalinks: true


# Setup
title:            uni stuff
tagline:         '"I get up. I walk. I fall down. Meanwhile, <a href="http://katieball.me" target="_blank">I keep</a> dancing". —Daniel Hillel.'
tagline:          'An Awesome Blog'
url:              roachhd.github.io/uni/
baseurl:          roachhd.github.io/uni/


author:
  name:           'Katie Ball'
  url:            https://twitter.com/mektball


paginate:         5


# Custom vars
version:          2.1.0


github:
  repo:           https://github.com/roachhd/uni

