# Dependencies
markdown:         redcarpet
highlighter:      pygments


# Permalinks
permalink:        pretty
relative_permalinks: true


# Setup
title:            zenlife
tagline:          'An Awesome life'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              roachhd.github.io/zenlife/
baseurl:          roachhd.github.io/zenlife/


author:
  name:           'Katie Ball'
  url:            https://twitter.com/mektball


paginate:         5


# Custom vars
version:          2.1.0


github:
  repo:           https://github.com/roachhd/zenlife


