# Dependencies
markdown:         kramdown
highlighter:      pygments

kramdown: 
 input: GFM

# Permalinks
permalink:        pretty
relative_permalinks: true


# Setup
title:            Uni Stuff
description:      'I get up. I walk. I fall down. <a href="http://katieball.me" target="_blank">Meanwhile</a>, I keep dancing.'
tagline:          'Study Period 4 2014'
url:              roachhd.github.io/uni
baseurl:          roachhd.github.io/uni


author:
  name:           'Katie Ball'
  url:            https://twitter.com/mektball


paginate:         10


# Custom vars
version:          2.1.0


github:
  repo:           https://github.com/roachhd/uni

categories: [WEB101, NET101, extra reading]


